name: 'Github actions workflow'
on: workflow_dispatch
permissions:
  id-token: write
  contents: read
jobs: 
  Terraformjobs:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.2
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: d280ce02-d0b3-4d9c-b0c2-1e2de8987bf1
        tenant-id: c1458e86-22a3-4b4c-b4af-89ecd5384a8f
        subscription-id: 5e4fafbb-ef69-4e17-8835-68030d81f758
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
      
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Terraform Validate
      id: validate
      run: terraform validate 
    
