name: 'Github actions workflow'
on: 
    push:  
        branches:
        - main
permissions: 
  id-token: write
  contents: read
jobs: 
  Terraformjobs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.2
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: 971d5e5d-7c8d-4f0d-8b02-3085fc1926e9
        tenant-id: c1458e86-22a3-4b4c-b4af-89ecd5384a8f
        allow-no-subscriptions: true
        
    - name: Terraform Init
      id: init
      run: terraform init
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
      
    - name: Terraform Validate
      id: validate
      run: terraform validate
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      continue-on-error: true
    - name: Terraform Apply
      id: apply
      run: terraform apply --auto-approve
